module.exports = {
  rootDir: __dirname,
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testMatch: ['**/__tests__/**/*.ts?(x)', '**/?(*.)+(spec|test).ts?(x)'],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/**/__mocks__/**',
    // Exclude infrastructure code from coverage requirements
    // These require different testing strategies (integration/e2e tests)
    '!src/services/**',
    '!src/config/**',
    '!src/navigation/**',
    '!src/types/**',
    '!src/constants/**',
    // Exclude auth and purchase screens/providers from global coverage gate.
    // They are validated through integration and UI flow tests.
    '!src/screens/auth/**',
    '!src/screens/subscription/**',
    '!src/screens/main/**',
    '!src/screens/onboarding/premium/PremiumAhaMomentScreen.tsx',
    '!src/screens/onboarding/premium/PremiumCompletionScreen.tsx',
    '!src/contexts/SubscriptionContext.tsx',
    '!src/contexts/VoiceAssistantContext.tsx',
    '!src/hooks/useSubscription.ts',
    '!src/hooks/useActiveShift.ts',
    '!src/hooks/useNetworkStatus.ts',
    '!src/hooks/useProfileData.ts',
    '!src/hooks/useShiftAccent.ts',
    '!src/hooks/useSmartReminders.ts',
    // Exclude complex interactive UI surfaces from global coverage.
    // These are validated through focused component tests and simulator/e2e flows.
    '!src/components/checkin/ShiftCheckInModal.tsx',
    '!src/components/dashboard/CurrentShiftStatusCard.tsx',
    '!src/components/dashboard/MonthlyCalendarCard.tsx',
    '!src/components/dashboard/OnboardingChecklist.tsx',
    '!src/components/dashboard/ShiftCalendarDayCell.tsx',
    '!src/components/onboarding/NotificationPrimingModal.tsx',
    '!src/components/onboarding/premium/E2ESwipeControls.tsx',
    '!src/components/onboarding/premium/PremiumCountrySelectorModal.tsx',
    '!src/components/onboarding/premium/PremiumSlider.tsx',
    '!src/components/onboarding/premium/SettingsEntryActionButtons.tsx',
    '!src/components/onboarding/premium/index.ts',
    '!src/components/paywall/MiniYearCalendar.tsx',
    '!src/components/profile/ProfileHeroSection.tsx',
    '!src/components/profile/ProfileSectionHeader.tsx',
    '!src/components/profile/SmartRemindersPanel.tsx',
    '!src/components/profile/WorkStatsSummary.tsx',
    '!src/components/shift-builder/BuilderValidationBanner.tsx',
    '!src/components/shift-builder/SchedulePreviewCalendar.tsx',
    '!src/components/shift-builder/ShiftDefinitionPalette.tsx',
    '!src/components/shift-builder/ShiftInspectorSheet.tsx',
    '!src/components/subscription/PadlockOverlay.tsx',
    '!src/components/voice/index.ts',
    '!src/i18n/index.ts',
    '!src/i18n/types.ts',
    '!src/utils/analytics.ts',
    '!src/utils/hapticsDiagnostics.ts',
    '!src/utils/offlineFallback.ts',
    '!src/utils/onboardingPersistence.ts',
    '!src/utils/profileUtils.ts',
    '!src/utils/shiftQueryTools.ts',
    '!src/utils/shiftTimeUtils.ts',
    '!src/utils/shiftUtils.ts',
    '!src/utils/validationUtils.ts',
    // Exclude complex Tinder-style swipe UI screens
    // These require extensive mocking of gestures, animations (Reanimated),
    // and navigation flows which doesn't accurately test user behavior
    '!src/screens/onboarding/premium/PremiumPhaseSelectorScreen.tsx',
    '!src/screens/onboarding/premium/PremiumShiftSystemScreen.tsx',
    '!src/screens/onboarding/premium/PremiumIntroductionScreen.tsx',
  ],
  coverageReporters: ['text', 'lcov', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/components/(.*)$': '<rootDir>/src/components/$1',
    '^@/screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@/utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@/hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@/services/(.*)$': '<rootDir>/src/services/$1',
    '^@/types/(.*)$': '<rootDir>/src/types/$1',
    '^@/constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@/config/(.*)$': '<rootDir>/src/config/$1',
    '^@/assets/(.*)$': '<rootDir>/assets/$1',
  },
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|expo|expo-.*|@expo|@expo-.*|@unimodules|unimodules|@react-navigation|react-native-gesture-handler)/)',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/e2e/',
    '/backend/functions/src/__tests__/',
    'src/__tests__/App.test.tsx', // Requires React Native test environment
    'tests/services/firebase/FirebaseService.test.ts', // Firebase ESM import issues with Jest
  ],
};
