import { StyleSheet } from 'react-native';

export const RYVRO_AUTH_COLORS = {
  void: '#02070b',
  ink: '#07121a',
  panel: 'rgba(8, 22, 31, 0.84)',
  panelStrong: 'rgba(13, 34, 48, 0.96)',
  cyan: '#20f4dc',
  blue: '#147cff',
  silver: '#d6e7f2',
  muted: '#9db2c2',
  line: 'rgba(191, 231, 255, 0.2)',
  error: '#ff8a80',
  white: '#f7fbff',
} as const;

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: RYVRO_AUTH_COLORS.void,
  },
  scroll: {
    flexGrow: 1,
    paddingHorizontal: 24,
  },
  inner: {
    flex: 1,
    paddingHorizontal: 24,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: RYVRO_AUTH_COLORS.line,
    backgroundColor: 'rgba(8, 22, 31, 0.72)',
    marginBottom: 24,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  appLogo: {
    width: 104,
    height: 104,
    alignSelf: 'center',
    marginBottom: 14,
  },
  title: {
    color: RYVRO_AUTH_COLORS.white,
    fontSize: 37,
    lineHeight: 43,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 10,
  },
  subtitle: {
    color: RYVRO_AUTH_COLORS.muted,
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '700',
    textAlign: 'center',
  },
  form: {
    gap: 12,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 138, 128, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 138, 128, 0.32)',
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 4,
  },
  errorBannerText: {
    color: RYVRO_AUTH_COLORS.error,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    flex: 1,
  },
  fieldGroup: {
    gap: 7,
    marginBottom: 4,
  },
  fieldLabel: {
    color: RYVRO_AUTH_COLORS.silver,
    fontSize: 14,
    fontWeight: '900',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(8, 22, 31, 0.78)',
    borderWidth: 1,
    borderColor: RYVRO_AUTH_COLORS.line,
    borderRadius: 20,
    paddingHorizontal: 16,
    minHeight: 58,
  },
  inputError: {
    borderColor: RYVRO_AUTH_COLORS.error,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: RYVRO_AUTH_COLORS.silver,
    fontSize: 17,
    fontWeight: '700',
  },
  eyeButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldError: {
    color: RYVRO_AUTH_COLORS.error,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 2,
  },
  forgotRow: {
    alignSelf: 'flex-end',
    marginTop: -4,
    marginBottom: 4,
    paddingVertical: 6,
  },
  forgotText: {
    color: RYVRO_AUTH_COLORS.cyan,
    fontSize: 14,
    fontWeight: '900',
  },
  primaryButton: {
    minHeight: 62,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    overflow: 'hidden',
    backgroundColor: RYVRO_AUTH_COLORS.cyan,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: RYVRO_AUTH_COLORS.void,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 18,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: RYVRO_AUTH_COLORS.line,
  },
  dividerText: {
    color: RYVRO_AUTH_COLORS.muted,
    fontSize: 14,
    fontWeight: '800',
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    minHeight: 58,
    backgroundColor: 'rgba(8, 22, 31, 0.78)',
    borderWidth: 1,
    borderColor: RYVRO_AUTH_COLORS.line,
    borderRadius: 20,
    marginBottom: 10,
  },
  socialButtonText: {
    color: RYVRO_AUTH_COLORS.silver,
    fontSize: 16,
    fontWeight: '900',
  },
  appleButton: {
    backgroundColor: RYVRO_AUTH_COLORS.silver,
    borderColor: RYVRO_AUTH_COLORS.silver,
  },
  appleButtonText: {
    color: RYVRO_AUTH_COLORS.void,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 28,
    flexWrap: 'wrap',
  },
  footerText: {
    color: RYVRO_AUTH_COLORS.muted,
    fontSize: 15,
    fontWeight: '700',
  },
  footerLink: {
    color: RYVRO_AUTH_COLORS.cyan,
    fontSize: 15,
    fontWeight: '900',
  },
  successState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  successIcon: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(32, 244, 220, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(32, 244, 220, 0.34)',
    marginBottom: 14,
  },
  successTitle: {
    color: RYVRO_AUTH_COLORS.white,
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '900',
    textAlign: 'center',
  },
  successBody: {
    color: RYVRO_AUTH_COLORS.muted,
    fontSize: 17,
    lineHeight: 25,
    fontWeight: '700',
    textAlign: 'center',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  iconContainer: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: 'rgba(32, 244, 220, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(32, 244, 220, 0.34)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  instructions: {
    color: RYVRO_AUTH_COLORS.muted,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  pollingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: RYVRO_AUTH_COLORS.line,
    backgroundColor: 'rgba(8, 22, 31, 0.62)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  pollingText: {
    color: RYVRO_AUTH_COLORS.silver,
    fontSize: 14,
    fontWeight: '800',
  },
  resendButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  resendButtonDisabled: {
    opacity: 0.5,
  },
  resendText: {
    color: RYVRO_AUTH_COLORS.cyan,
    fontSize: 15,
    fontWeight: '900',
  },
  skipButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  skipText: {
    color: RYVRO_AUTH_COLORS.muted,
    fontSize: 15,
    fontWeight: '800',
  },
});
